services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./tests:/tests

  test:
    build: .
    command: ["python", "-m", "unittest", "discover", "-s", "tests"]
    volumes:
      - ./app:/app
      - ./tests:/tests